Repository MetaTech-dev/health-quiz-server, pull requests merged in 2021-01, with the labels that each got.

#20 feat(Person): create person query and resolver
  src/Person/resolvers.js
  src/Person/typeDefs.js
Labels: enhancement

#34 Goals
  src/Goal/resolvers.js
  src/Goal/typeDefs.js
  src/Person/typeDefs.js
  src/User/typeDefs.js
  src/schema.js
Labels: bug, enhancement

#35 fix(stuff): provider resolver need id param, healthReportsData export
  src/HealthReport/resolvers.js
  src/Provider/resolvers.js
Labels: bug
